
DROP SEQUENCE MYSEQ;
DROP TABLE  MYBOARD;

CREATE SEQUENCE MYSEQ;

--번호 , 작성자 , 제목 , 내용 ,날짜
CREATE TABLE MYBOARD(
	MYNO NUMBER PRIMARY KEY,
	MYNAME VARCHAR2(500) NOT NULL,
	MYTITLE VARCHAR2(2000) NOT NULL,
	MYCONTENT VARCHAR2(4000) NOT NULL,
	MYDATE DATE NOT NULL
);

INSERT INTO MYBOARD VALUES(MYSEQ.NEXTVAL , '관리자', '게시판테스트' , '테스트중1234',SYSDATE);

INSERT INTO MYBOARD VALUES(MYSEQ.NEXTVAL , '홍길동', '1빠' , '111111',SYSDATE);

SELECT * FROM MYBOARD ORDER BY MYNO DESC;

 SELECT MYNO , MYNAME , MYTITLE , MYCONTENT , MYDATE FROM MYBOARD ORDER BY MYNO DESC 