/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.19
 * Generated at: 2019-09-07 16:01:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1565815268000L));
    _jspx_dependants.put("jar:file:/C:/Workspace_Web/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/OPT222/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<title>Online Personal Training</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/full-page-scroll.css\">\r\n");
      out.write("\t<link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>\r\n");
      out.write("\t<link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"image/favicon-32x32.png\">\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write(".Menu { /*상단 메뉴바 전체부분의  div*/\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("    height: 80px;\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    z-index: 70;\r\n");
      out.write("/*     border-bottom: 1px solid #e6e6e6; */\r\n");
      out.write("}\r\n");
      out.write(".topmenu li {\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("\tmargin: 3px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tfont-size: 10px;\r\n");
      out.write("\ttop: 6px;\r\n");
      out.write("}\r\n");
      out.write(".innerMenu { /*상단 메뉴바 안에 들어가는 컨텐츠 부분의 div*/\r\n");
      out.write("\tz-index: 70;\r\n");
      out.write("\twidth: 1200px; /*가운데정렬을 위해 고정으로 길이줌*/\r\n");
      out.write("\theight: 80px;\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\t\r\n");
      out.write("\t/* 전체 가운데 정렬, fixed일 경우는 이렇게 가운데 정렬*/\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    transform: translate(-50%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menulogo{ /*로고부분 (따로뺌)*/\r\n");
      out.write("\tfloat : left;\r\n");
      out.write("\tmargin-right: 25px;\r\n");
      out.write("}\r\n");
      out.write(".menulist { /*메뉴 리스트 a링크들 / 로고와 구분하려고 따로 줌 */\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    width: 120px;\r\n");
      out.write("    margin-left: 27px;\r\n");
      out.write("    margin-right: 11px;\r\n");
      out.write("    font-size: 24px;\r\n");
      out.write("    display: block;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    text-shadow: -1px 0 #545252, 0 1px #545252, 1px 0 #545252, 0 -1px #545252;\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t.section1 {\r\n");
      out.write("\t\tbackground: url(\"main_image/exercise.png\");\r\n");
      out.write("\t\tbackground-size: cover;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.section2 {\r\n");
      out.write("\t\tbackground: url(\"main_image/running.png\");\r\n");
      out.write("\t\tbackground-size: cover;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.section3 {\r\n");
      out.write("\t\r\n");
      out.write("\t\tbackground: url(main_image/veg.png);\r\n");
      out.write("\t\tbackground-size: cover;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.section4 {\r\n");
      out.write("\t\tbackground: url(\"main_image/cabbage.png\"); \r\n");
      out.write("\t\tbackground-size: cover;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.section5 {\r\n");
      out.write("\t\tbackground: url(\"main_image/sal3.png\");\r\n");
      out.write("\t\tbackground-size: cover;\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\tsection .section_title {\r\n");
      out.write("\tfont-family: 'Open Sans';\r\n");
      out.write("    font-style: normal;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    margin-top: -60px;\r\n");
      out.write("    /* top: 50%; */\r\n");
      out.write("    transform: translateY(-50%);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tspan {\r\n");
      out.write("\t\tfont-size: 5em;\r\n");
      out.write("\t\tfont-style: normal;\r\n");
      out.write("\t\tcolor: #fff;\r\n");
      out.write("\t}\r\n");
      out.write("\tp{\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("    font-style: normal;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-size: 25px;\r\n");
      out.write("    top: 32px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.section_background{\r\n");
      out.write("   \t width: 100%;\r\n");
      out.write("   \t height: 100%;\r\n");
      out.write("   \t background-color: black;\r\n");
      out.write("   \t opacity: 0.2;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t</style>\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header class=\"header\">\r\n");
      out.write("\t\t<div class=\"Menu\">\r\n");
      out.write("\t\t\t<div class =\"innerMenu\">\r\n");
      out.write("\t\t\t\t<ul class=\"topmenu\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a class = \"menulogo\" href=\"#\" title=\"OPT 메인으로 이동\">\r\n");
      out.write("\t\t\t\t\t\t\t<img alt=\"main\" src=\"image/logo2_w.png\" width=120px;>\r\n");
      out.write("\t\t\t\t\t\t</a> \r\n");
      out.write("\t\t\t\t\t\t<a class = \"menulist\" href=\"opt_brand.jsp\">OPT</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a class = \"menulist\" href=\"video.do?command=videoList&page=1&videoarea=main\">O-Tube</a>\r\n");
      out.write("\t\t\t\t\t\t<a class = \"menulist\" href=\"item.do?command=itemlist&page=1\">O-Food</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a class = \"menulist\" href=\"service.do?command=faqlist&page=1\">고객지원</a>\r\n");
      out.write("\t\t\t\t\t</li> \t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t");
 if(session.getAttribute("memdto") == null) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"menulist\" href=\"login.jsp?Flag=0\">로그인</a>\r\n");
      out.write("\t\t\t\t\t");
 } else {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"menulist\" href=\"login.do?command=logout\">로그아웃</a>\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t<a class=\"menulist\" href=\"opt.do?command=mypage\">마이페이지</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"main\" class=\"scroll-container\">\r\n");
      out.write("\t\t<section class=\"section1\">\r\n");
      out.write("\t\t\t<div class=\"section_background\"></div>\r\n");
      out.write("\t\t\t<div class=\"section_title\">\r\n");
      out.write("\t\t\t\t<span>어디서나 함께하는 OPT</span>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<strong>Solutions Are Often Closer Than You Think</strong>\r\n");
      out.write("\t\t\t\t</p>\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<section class=\"section2\">\r\n");
      out.write("\t\t\t<div class=\"section_background\"></div>\r\n");
      out.write("\t\t\t<div class=\"section_title\">\r\n");
      out.write("\t\t\t\t<span>시작했다면 포기하지 마세요</span>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<strong>It`s Only Crazy Until You Do It</strong>\r\n");
      out.write("\t\t\t\t</p>\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<section class=\"section3\">\r\n");
      out.write("\t\t\t<div class=\"section_background\"></div>\r\n");
      out.write("\t\t\t<div class=\"section_title\">\r\n");
      out.write("\t\t\t\t<span>체중 감량은 허황된 꿈이 아니다</span>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<strong>Weight Loss In No Pie In The Sky</strong>\r\n");
      out.write("\t\t\t\t</p>\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<section class=\"section4\">\r\n");
      out.write("\t\t\t<div class=\"section_background\"></div>\r\n");
      out.write("\t\t\t<div class=\"section_title\">\r\n");
      out.write("\t\t\t\t<span>신선한 음식을 제공합니다</span>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<strong>Now Available On OPT</strong>\r\n");
      out.write("\t\t\t\t</p>\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<section class=\"section5\">\r\n");
      out.write("\t\t\t<div class=\"section_background\"></div>\r\n");
      out.write("\t\t\t<div class=\"section_title\">\r\n");
      out.write("\t\t\t\t<span>여러분의 건강을 책임집니다</span>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<strong>A Sound Mind In A Sound Body</strong>\r\n");
      out.write("\t\t\t\t</p>\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script src=\"js/full-page-scroll.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tnew fullScroll({\r\n");
      out.write("\t\t\tdisplayDots: true,\r\n");
      out.write("\t\t\tdotsPosition: 'left',\r\n");
      out.write("\t\t\tanimateTime: 0.7,\r\n");
      out.write("\t\t\tanimateFunction: 'ease'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
