DROP SEQUENCE BOARDNOSEQ;
DROP SEQUENCE GROUPNOSEQ;
DROP TABLE ANSWERBOARD;
--글번호 +1 시퀀스
CREATE SEQUENCE BOARDNOSEQ;
--그룹번호 +1 시퀀스
CREATE SEQUENCE GROUPNOSEQ;
--글번호 , 그룹번호 ,그룹순서, 제목탭 ,삭제여부, 제목 , 내용 ,작성자 , 작성일
CREATE TABLE ANSWERBOARD(
	BOARDNO NUMBER PRIMARY KEY,
	GROUPNO NUMBER NOT NULL,
	GROUPSQ NUMBER NOT NULL,
	TITLETAB NUMBER NOT NULL,
	DELFLAG VARCHAR2(2) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WRITER VARCHAR2(1000) NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTRAINT ANSWER_DELFLAG_CHK CHECK (DELFLAG IN ('Y','N'))
);

SELECT * FROM ANSWERBOARD 
ORDER BY GROUPNO DESC, GROUPSQ;

INSERT INTO ANSWERBOARD VALUES(BOARDNOSEQ.NEXTVAL,GROUPNOSEQ.NEXTVAL,1,0,'N','1번글','1번내용','1번',SYSDATE);

UPDATE ANSWERBOARD SET GROUPSQ = GROUPSQ + 1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 1)
AND GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO = 1);

INSERT INTO ANSWERBOARD VALUES(BOARDNOSEQ.NEXTVAL,
(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 1),
(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO = 1)+1,
(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO = 1)+1,
'N','1번답글','답글','답글내용',SYSDATE);



INSERT INTO ANSWERBOARD VALUES(BOARDNOSEQ.NEXTVAL,GROUPNOSEQ.NEXTVAL,1,0,'1번글','1번내용','1번',SYSDATE);
INSERT INTO ANSWERBOARD VALUES(BOARDNOSEQ.NEXTVAL,GROUPNOSEQ.NEXTVAL,1,0,'2번글','2번내용','2번',SYSDATE);
INSERT INTO ANSWERBOARD VALUES(BOARDNOSEQ.NEXTVAL,GROUPNOSEQ.NEXTVAL,1,0,'3번글','3번내용','3번',SYSDATE);
INSERT INTO ANSWERBOARD VALUES(BOARDNOSEQ.NEXTVAL,GROUPNOSEQ.NEXTVAL,1,0,'4번글','4번내용','4번',SYSDATE);
INSERT INTO ANSWERBOARD VALUES(BOARDNOSEQ.NEXTVAL,GROUPNOSEQ.NEXTVAL,1,0,'5번글','5번내용','5번',SYSDATE);

INSERT INTO ANSWERBOARD VALUES(BOARDNOSEQ.NEXTVAL,
(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=5),
(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=5)+1,
(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=5)+1,
'5번답글','답글1','6번',SYSDATE);

UPDATE ANSWERBOARD SET GROUPSQ = GROUPSQ +1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 5)
AND GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO = 5);

INSERT INTO ANSWERBOARD VALUES(BOARDNOSEQ.NEXTVAL,
(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=5),
(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=5)+1,
(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=5)+1,
'5번답글2','답글2','7번',SYSDATE);

UPDATE ANSWERBOARD SET GROUPSQ = GROUPSQ +1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 6)
AND GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO = 7);


INSERT INTO ANSWERBOARD VALUES(BOARDNOSEQ.NEXTVAL,
(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=7),
(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=7)+1,
(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=7)+1,
'5번답글답글','답답글1','8번',SYSDATE);

--4번 답글없어도 무조건 업데이트부터
--? 부모의 글번호
UPDATE ANSWERBOARD SET GROUPSQ = GROUPSQ +1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = ?)
AND GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO = ?);

--?부모의 글번호
INSERT INTO ANSWERBOARD VALUES(BOARDNOSEQ.NEXTVAL,
(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=?),
(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=?)+1,
(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=?)+1,
?,?,?,SYSDATE);
--제목,내용,작성자

UPDATE ANSWERBOARD SET DELFLAG = ? WHERE BOARDNO = ?;

UPDATE ANSWERBOARD SET GROUPSQ = GROUPSQ +1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 4)
AND GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO = 4);

INSERT INTO ANSWERBOARD VALUES(BOARDNOSEQ.NEXTVAL,
(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=9),
(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=9)+1,
(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=9)+1,
'4번답글답글','답글답글1','10번',SYSDATE);

UPDATE ANSWERBOARD SET GROUPSQ = GROUPSQ +1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 4)
AND GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO = 4);

INSERT INTO ANSWERBOARD VALUES(BOARDNOSEQ.NEXTVAL,
(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=4),
(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=4)+1,
(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=4)+1,
'4번답글2','답글2','11번',SYSDATE);

INSERT INTO ANSWERBOARD VALUES(BOARDNOSEQ.NEXTVAL,
(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=11),
(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=11)+1,
(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=11)+1,
'4번답글답글2','답글2','12번',SYSDATE);

DELETE FROM ANSWERBOARD 
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 5) 
AND GROUPSQ >= (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO = 5);

SELECT * FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSQ;
--------------------------------------------------------------------------------------------------------------------------------------------

DROP SEQUENCE BSEQ;
DROP SEQUENCE GSEQ;
DROP TABLE ABOARD;
--글번호 +1 시퀀스
CREATE SEQUENCE BSEQ;
--그룹번호 +1 시퀀스
CREATE SEQUENCE GSEQ;
--글번호 , 그룹번호 ,그룹순서, 제목탭 , 제목 , 내용 ,작성자 , 작성일
CREATE TABLE ABOARD(
	BOARDNO NUMBER PRIMARY KEY,
	GROUPNO NUMBER NOT NULL,
	GROUPSQ NUMBER NOT NULL,
	TITLETAB NUMBER NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WRITER VARCHAR2(1000) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO ABOARD VALUES(BSEQ.NEXTVAL,GSEQ.NEXTVAL,1,0,'1번글','1번내용','1번',SYSDATE);
INSERT INTO ABOARD VALUES(BSEQ.NEXTVAL,GSEQ.NEXTVAL,1,0,'2번글','2번내용','2번',SYSDATE);
INSERT INTO ABOARD VALUES(BSEQ.NEXTVAL,GSEQ.NEXTVAL,1,0,'3번글','3번내용','3번',SYSDATE);
INSERT INTO ABOARD VALUES(BSEQ.NEXTVAL,GSEQ.NEXTVAL,1,0,'4번글','4번내용','4번',SYSDATE);
INSERT INTO ABOARD VALUES(BSEQ.NEXTVAL,GSEQ.NEXTVAL,1,0,'5번글','5번내용','5번',SYSDATE);

SELECT * FROM ABOARD ORDER BY GROUPNO DESC , GROUPSQ;

UPDATE ABOARD SET GROUPSQ = GROUPSQ + 1
WHERE GROUPNO = (SELECT GROUPNO FROM ABOARD WHERE BOARDNO = 7)
AND GROUPSQ > (SELECT GROUPSQ FROM ABOARD WHERE BOARDNO = 7);

INSERT INTO ABOARD VALUES(BSEQ.NEXTVAL,
(SELECT GROUPNO FROM ABOARD WHERE BOARDNO = 7),
(SELECT GROUPSQ FROM ABOARD WHERE BOARDNO = 7)+1,
(SELECT TITLETAB FROM ABOARD WHERE BOARDNO = 7)+1,
'5번답글답글','답글2','유저2',SYSDATE);

UPDATE ABOARD SET GROUPSQ = GROUPSQ + 1
WHERE GROUPNO = (SELECT GROUPNO FROM ABOARD WHERE BOARDNO = 10)
AND GROUPSQ > (SELECT GROUPSQ FROM ABOARD WHERE BOARDNO = 10);

INSERT INTO ABOARD VALUES(BSEQ.NEXTVAL,
(SELECT GROUPNO FROM ABOARD WHERE BOARDNO = 10),
(SELECT GROUPSQ FROM ABOARD WHERE BOARDNO = 10)+1,
(SELECT TITLETAB FROM ABOARD WHERE BOARDNO = 10)+1,
'4번답글답글','답글11','유저5',SYSDATE);



UPDATE ABOARD SET GROUPSQ = GROUPSQ + 1
WHERE GROUPNO = (SELECT GROUPNO FROM ABOARD WHERE BOARDNO = 16)
AND GROUPSQ > (SELECT GROUPSQ FROM ABOARD WHERE BOARDNO = 16);


INSERT INTO ABOARD VALUES(BSEQ.NEXTVAL,
(SELECT GROUPNO FROM ABOARD WHERE BOARDNO = 16),
(SELECT GROUPSQ FROM ABOARD WHERE BOARDNO = 16)+1,
(SELECT TITLETAB FROM ABOARD WHERE BOARDNO = 16)+1,
'1번답글','답글11','유저1',SYSDATE);



SELECT * FROM ABOARD ORDER BY GROUPNO DESC , GROUPSQ;

DELETE FROM ABOARD 
WHERE GROUPNO = (SELECT GROUPNO FROM ABOARD WHERE BOARDNO = 7)
AND GROUPSQ > (SELECT GROUPSQ FROM ABOARD WHERE BOARDNO = 7);